[book]
title = "Ducia 开发手册"
authors = ["corain"]
language = "zh-CN"
description = "Ducia Listing Framework — 轻量级文档管理系统"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/FleetingLore/ducia-listing-framework"
edit-url-template = "https://github.com/FleetingLore/ducia-listing-framework/edit/main/book/src/{path}"
